version: '3'

services:

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=post
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
